version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "io.debezium:debezium-testing-testcontainers"
        versions: [ ">=2.7.4" ]
      - dependency-name: "org.asynchttpclient:async-http-client"
        versions: [ ">=3.0.0" ]
